{% set name = "qcfractal" %}
{% set version = "0.70" %}
# pattern for unpublished commits {% set version = "0.50b13.post52+gbb2748c85" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # unpublished - any repo commit. sync commit in git_rev below with commit and distance in version above
  #git_url: https://github.com/MolSSI/QCFractal.git
  #git_rev: bb2748c8534b267e33f894ef71a2d9a6da50c5af
  #sha256: 81cdc093dda5e7739496088b70be7c3110fb691b4fdf22c7e3b58377450e2081
  # published tags.
  - url: https://files.pythonhosted.org/packages/source/q/qcportal/qcportal-{{ version }}.tar.gz
    sha256: b29b3b4ac8b6d961595c74810e189e0636f8d1e7c4a867cf331ed7c6552784ce
    folder: qcportal
  - url: https://files.pythonhosted.org/packages/source/q/qcfractalcompute/qcfractalcompute-{{ version }}.tar.gz
    sha256: 547c88dfc6fcd07c687239c34dcaefcc83831c31e3430500ee8a3ee363015611
    folder: qcfractalcompute
  - url: https://files.pythonhosted.org/packages/source/q/qcfractal/qcfractal-{{ version }}.tar.gz
    sha256: 9f2ba22060dc86e37b3262c020d70f8ee049d4a38ed2d7643c9e3735fe003866
    folder: qcfractal
  - url: https://files.pythonhosted.org/packages/source/q/qcarchivetesting/qcarchivetesting-{{ version }}.tar.gz
    sha256: 0d03ec3d2d4cbd42b1db3a5a3002e8fc3bcfe5e38cd6a411805c49dd8b5fe4d1
    folder: qcarchivetesting

build:
  number: 0

outputs:
  - name: qcportal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcportal
    requirements:
      host:
        - python {{ python_min }},<3.14.0
        - pip
        - setuptools >=78.0
        - versioningit
      run:
        - python >={{ python_min }},<3.14.0
        - numpy
        - msgpack-python
        - requests
        - pyyaml
        - pydantic >=2.11,<3.0a0
        - pydantic-settings
        - zstandard
        - apsw >=3.42
        - qcelemental >=0.30,<0.70a0
        - tabulate
        - tqdm
        - pandas
        - pyjwt >=2.10
        - packaging
        - python-dateutil
        - pytz
    test:
      imports:
        - qcportal
      requires:
        - python {{ python_min }},<3.14.0
        - pip
      commands:
        - test -f $SP_DIR/qcportal/__init__.py
        #- pip check
        - python -c "import qcportal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Python library for interacting with QCArchive/QCFractal servers

  - name: qcfractalcompute
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractalcompute
    requirements:
      host:
        - python {{ python_min }},<3.14.0
        - pip
        - setuptools >=78.0
        - versioningit
      run:
        - python >={{ python_min }},<3.14.0
        - qcportal ={{ version }}
        - parsl
        - __unix  # [unix]
    test:
      imports:
        - qcfractalcompute
      requires:
        - python {{ python_min }},<3.14.0
        - pip
      commands:
        - test -f $SP_DIR/qcfractalcompute/__init__.py
        #- pip check
        - python -c "import qcfractalcompute as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-compute-manager --help
    about:
      summary: Distributed worker package for QCArchive

  - name: qcfractal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractal
    requirements:
      host:
        - python {{ python_min }},<3.14.0
        - pip
        - setuptools >=78.0
        - versioningit
      run:
        - python >={{ python_min }},<3.14.0
        - flask
        - flask-jwt-extended
        - flask-cors
        - waitress
        - bcrypt
        - sqlalchemy >=2.0
        - alembic
        - psycopg2
        - geoip2
        - boto3
        - torsiondrive
        - qcmanybody
        - geometric >=1.1.1

        - qcfractalcompute ={{ version }}
        - __unix  # [unix]
    test:
      imports:
        - qcfractal.snowflake
      requires:
        - python {{ python_min }},<3.14.0
        - pip
      commands:
        - test -f $SP_DIR/qcfractal/__init__.py
        #- pip check
        - python -c "import qcfractal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-server --help
    about:
      summary: Database and Web API for the QCArchive project

  - name: qcarchivetesting
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcarchivetesting
    requirements:
      host:
        - python {{ python_min }},<3.14.0
        - pip
        - setuptools >=78.0
        - versioningit
      run:
        - python >={{ python_min }},<3.14.0
        - qcfractal ={{ version }}
        - qcengine >=0.34,<0.70a0
        - pytest
        - deepdiff
    test:
      imports:
        - qcarchivetesting.helpers
      requires:
        - python {{ python_min }},<3.14.0
        - pip
      commands:
        - test -f $SP_DIR/qcarchivetesting/__init__.py
        #- pip check
        - python -c "import qcarchivetesting as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Additional testing fixtures and functions for the QCArchive project

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://molssi.github.io/QCFractal/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/main/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/license/bsd-3-clause/
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
  feedstock-name: qcfractal
  recipe-maintainers:
    - lnaden
    - bennybp
